arxiv:
  categories:  # 文章类型
    - physics.plasm-ph
    - physics.acc-ph
    - physics.optics
    - physics.flu-dyn
    - physics.atom-ph
    - physics.comp-ph

llm:
  model_name: 'deepseek-chat'  # 使用的LLM模型
